sonar.host.url=http://192.168.11.200:9002
sonar.token=squ_234724787b38c1b45a4438ad7bdb22db28176fb4
sonar.projectKey=opencodetest
sonar.projectName=ProjectFlow
sonar.sources=src
sonar.tests=src/__tests__
sonar.test.inclusions=**/*.test.ts,**/*.test.tsx
sonar.javascript.lcov.reportPaths=coverage/lcov.info
sonar.coverage.exclusions=src/components/ui/**
